### PR TITLE
sample CAS WWW-Authenticate header on 401 responses

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
@jonvellacott 

So, I have no clue is this is the correct syntax or not, but this is a sample of a simple WWW-Authenticate header indicating CAS authentication is needed. The actual header for Ekko looks like this:

WWW-Authenticate: CAS realm="ekko", casUrl="https://thekey.me/cas/", service="https://services.gcx.org/ekko/v1/auth/login"

but for now if it just includes "CAS realm=\"something\"" that is enough to meet the HTTP spec.

part of the http spec is that 401 responses must include a WWW-Authenticate header, and certain versions of Android really care about it's presence. see: https://stackoverflow.com/questions/14550131/http-basic-authentication-issue-on-android-jelly-bean-4-1-using-httpurlconnectio

**Comment by frett** [comment]
for responses that are unauthorized for a reason other than CAS, use a different scheme and realm.

e.g. `WWW-Authenticate: Unauthorized realm="api"`

**Comment by frett** [comment]
if you can confirm this is the right syntax, I can search through all the controllers and add in the code for each unauthorized

**Comment by jonvellacott** [comment]
Very close! To escape a double-quote, you put 2 double-quotes:

```rtn.Headers.Add("WWW-Authenticate", "CAS realm=""gma""")```

**Comment by jonvellacott** [comment]
I'll go ahead and implement this in a slightly different way... I'd rather throw this exception in ValidateSession() instead of on each controller.

**Comment by jonvellacott** [comment]
Here's an example: https://stage.sbr.global-registry.org/api/measurements/assignments?token=invalid

I'll go through and do the non-cas 401's later...

**Comment by jonvellacott** [comment]
All 401's now contain a WWW-Authenticate. If it is non cas related (e.g. you don't have a sufficient team-role) - the header returns: `WWW-Authenticate: Unauthorized realm="api"`

**Pull request closed without merging**
